version: '3.8'

services:
  ravendb:
    container_name: ravendb
    image: ravendb/ravendb:6.2.1-ubuntu.22.04-x64
    volumes:
      - ravendb_data:/var/lib/ravendb/data     
    ports:
      - "8080:8080"    
    environment:
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
    networks:
      - crudy_network

  crudy:
    image: crudy
    container_name: crudy
    depends_on:
      - ravendb
    networks:
      - crudy_network
    ports:
      - "5000:5000"
    environment:
      - RavenSettings:Urls:0=http://ravendb:8080
      - RAVEN_DatabaseName=crudy
      - ASPNETCORE_HTTP_PORTS=5000


networks:
  crudy_network:
    driver: bridge

volumes:
  ravendb_data:
    driver: local